import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // Cookery Courses
  {
    id: 'kitchen-management',
    title: 'Certificate IV in Kitchen Management',
    description:
      'Learn professional kitchen management skills and culinary techniques.',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78 weeks',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'NSW Food Safety Supervisor',
    description: 'Learn food safety and hygiene management.',
    category: 'cookery',
    type: 'short-course',
    duration: '1 day',
    price: 180,
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },
  // Hospitality Courses
  {
    id: 'hospitality-diploma',
    title: 'Diploma of Hospitality Management',
    description: 'Comprehensive hospitality management skills.',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78 weeks / 104 weeks',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: 'Advanced Diploma of Hospitality Management',
    description: 'Advanced hospitality management and leadership skills.',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104 weeks',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },
  // Fitness Courses
  {
    id: 'fitness-cert-iii',
    title: 'Certificate III in Fitness',
    description: 'Foundation fitness and personal training skills.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52 weeks',
    image: '/courses/fitness/ABM_Fitness_Photos_13.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: 'Certificate IV in Fitness',
    description: 'Advanced fitness training and instruction skills.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 weeks',
    image: '/courses/fitness/ABM_Fitness_Photos_10.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: 'Certificate III in Fitness (Fast Track)',
    description: 'Accelerated sports coaching and training program.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12 weeks / 24 weeks',
    image: '/courses/fitness/ABM_Fitness_Photos_11.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: 'Certificate IV in Fitness (Fast Track)',
    description: 'Advanced sports coaching and development program.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12 weeks / 24 weeks',
    image: '/courses/fitness/ABM_Fitness_Photos_9.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: 'Diploma of Sport',
    description: 'Comprehensive sports coaching and development program.',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52 weeks',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },
  // Business Courses
  {
    id: 'business-cert-iv',
    title: 'Certificate IV in Business',
    description: 'Foundation business skills and knowledge.',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 weeks',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: 'Diploma of Business',
    description: 'Comprehensive business management and leadership skills.',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52 weeks',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: 'Advanced Diploma of Business',
    description: 'Advanced business strategy and management skills.',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 weeks',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: 'Graduate Diploma of Management (Learning)',
    description: 'Postgraduate level management and leadership skills.',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52 weeks',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },

  // Project Management Courses
  {
    id: 'project-cert-iv',
    title: 'Certificate IV in Project Management Practice',
    description: 'Foundation project management skills and methodologies.',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 weeks',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: 'Diploma of Project Management',
    description: 'Comprehensive project management and leadership skills.',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52 weeks',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: 'Advanced Diploma of Program Management',
    description: 'Advanced project management and strategic planning skills.',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 weeks',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },

  // HR Courses
  {
    id: 'hr-certificate-iv',
    title: 'Certificate IV in Human Resource Management',
    description: 'Develop HR skills for entry-level positions.',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 weeks',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'certificate-iv'],
  },
  {
    id: 'hr-diploma',
    title: 'Diploma of Human Resource Management',
    description: 'Advanced HR management and strategic thinking.',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '78 weeks',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'diploma'],
  },
  {
    id: 'hr-advanced-diploma',
    title: 'Advanced Diploma of Human Resource Management',
    description: 'Senior HR leadership and strategic management skills.',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 weeks',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'leadership', 'advanced-diploma'],
  },

  // Health & Wellness Courses
  {
    id: 'health-services-assistance',
    title: 'HLT33115 Certificate III in Health Services Assistance',
    description:
      'Start your healthcare career with this comprehensive nursing support pathway including English language support and 80 hours of work placement.',
    category: 'health',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '16 weeks',
    image: '/courses/health/health_1.png',
    link: '/health-and-wellness-courses/hlt33115-certificate-iii-in-health-services-assistance',
    tags: [
      'health',
      'nursing',
      'healthcare',
      'certificate-iii',
      'work-placement',
    ],
  },

  // Custom Programs
  {
    id: 'custom-programs',
    title: 'Custom Programs',
    description:
      'Tailored programs for institutions, universities, and colleges. We partner with educational institutions to deliver customized programs that match their curriculum, learning goals, and student needs.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: 'Flexible',
    image: '/custom_program_1.png',
    link: '/custom-programs',
    tags: ['custom', 'programs', 'tailored', 'institutions', 'partnership'],
  },
];
