import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // Cookery Courses
  {
    id: 'kitchen-management',
    title: 'Certificate IV in Kitchen Management',
    description:
      'Pelajari keterampilan manajemen dapur profesional dan teknik memasak.',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78 minggu',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'NSW Food Safety Supervisor',
    description: 'Pelajari keamanan pangan dan manajemen kebersihan.',
    category: 'cookery',
    type: 'short-course',
    duration: '1 hari',
    price: 180,
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },
  {
    id: 'rsa',
    title: 'Responsible Service of Alcohol (RSA) - NSW',
    description: 'Prinsip-prinsip Pelayanan Alkohol yang Bertanggung Jawab.',
    category: 'hospitality',
    type: 'short-course',
    duration: '1 hari',
    price: 189,
    image: '/rsa_banner.png',
    link: '/cookery-and-hospitality-courses/rsa',
    tags: ['RSA', 'Alcohol', 'liquor laws', 'nsw'],
  },
  // Hospitality Courses
  {
    id: 'hospitality-diploma',
    title: 'Diploma of Hospitality Management',
    description: 'Keterampilan manajemen perhotelan yang komprehensif.',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78 minggu / 104 minggu',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: 'Advanced Diploma of Hospitality Management',
    description: 'Keterampilan manajemen dan kepemimpinan perhotelan tingkat lanjut.',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104 minggu',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },
  // Fitness Courses
  {
    id: 'fitness-cert-iii',
    title: 'Certificate III in Fitness',
    description: 'Keterampilan dasar kebugaran dan pelatihan personal.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52 minggu',
    image: '/courses/fitness/ABM_Fitness_Photos_13.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: 'Certificate IV in Fitness',
    description: 'Keterampilan pelatihan dan instruksi kebugaran tingkat lanjut.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 minggu',
    image: '/courses/fitness/ABM_Fitness_Photos_10.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: 'Certificate III in Fitness (Fast Track)',
    description: 'Program pelatihan coaching olahraga yang dipercepat.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12 minggu / 24 minggu',
    image: '/courses/fitness/ABM_Fitness_Photos_11.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: 'Certificate IV in Fitness (Fast Track)',
    description: 'Program coaching dan pengembangan olahraga tingkat lanjut.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12 minggu / 24 minggu',
    image: '/courses/fitness/ABM_Fitness_Photos_9.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: 'Diploma of Sport',
    description: 'Program coaching dan pengembangan olahraga yang komprehensif.',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52 minggu',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },
  // Business Courses
  {
    id: 'business-cert-iv',
    title: 'Certificate IV in Business',
    description: 'Keterampilan dan pengetahuan bisnis dasar.',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 minggu',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: 'Diploma of Business',
    description: 'Keterampilan manajemen dan kepemimpinan bisnis yang komprehensif.',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52 minggu',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: 'Advanced Diploma of Business',
    description: 'Keterampilan strategi dan manajemen bisnis tingkat lanjut.',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 minggu',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: 'Graduate Diploma of Management (Learning)',
    description: 'Keterampilan manajemen dan kepemimpinan tingkat pascasarjana.',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52 minggu',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },

  // Project Management Courses
  {
    id: 'project-cert-iv',
    title: 'Certificate IV in Project Management Practice',
    description: 'Keterampilan dan metodologi manajemen proyek dasar.',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 minggu',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: 'Diploma of Project Management',
    description: 'Keterampilan manajemen dan kepemimpinan proyek yang komprehensif.',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52 minggu',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: 'Advanced Diploma of Program Management',
    description: 'Keterampilan manajemen proyek dan perencanaan strategis tingkat lanjut.',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 minggu',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },

  // HR Courses
  {
    id: 'hr-certificate-iv',
    title: 'Certificate IV in Human Resource Management',
    description: 'Kembangkan keterampilan HR untuk posisi tingkat pemula.',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 minggu',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'certificate-iv'],
  },
  {
    id: 'hr-diploma',
    title: 'Diploma of Human Resource Management',
    description: 'Manajemen HR tingkat lanjut dan pemikiran strategis.',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '78 minggu',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'diploma'],
  },
  {
    id: 'hr-advanced-diploma',
    title: 'Advanced Diploma of Human Resource Management',
    description: 'Keterampilan kepemimpinan HR senior dan manajemen strategis.',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 minggu',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'leadership', 'advanced-diploma'],
  },

  // Health & Wellness Courses
  {
    id: 'health-services-assistance',
    title: 'HLT33115 Certificate III in Health Services Assistance',
    description:
      'Mulai karir kesehatan Anda dengan jalur dukungan keperawatan komprehensif ini termasuk dukungan bahasa Inggris dan 80 jam penempatan kerja.',
    category: 'health',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '16 minggu',
    image: '/courses/health/health_1.png',
    link: '/health-and-wellness-courses/hlt33115-certificate-iii-in-health-services-assistance',
    tags: [
      'health',
      'nursing',
      'healthcare',
      'certificate-iii',
      'work-placement',
    ],
  },

  // Custom Programs
  {
    id: 'custom-programs',
    title: 'Program Khusus',
    description:
      'Program yang disesuaikan untuk institusi, universitas, dan perguruan tinggi. Kami bermitra dengan institusi pendidikan untuk memberikan program khusus yang sesuai dengan kurikulum, tujuan pembelajaran, dan kebutuhan siswa mereka.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: 'Fleksibel',
    image: '/custom_program_1.png',
    link: '/custom-programs',
    tags: ['custom', 'programs', 'tailored', 'institutions', 'partnership'],
  },
];
