import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // Cookery Courses
  {
    id: 'kitchen-management',
    title: 'Certificate IV in Kitchen Management',
    description:
      '学习专业的厨房管理技能和烹饪技术。',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78周',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'NSW Food Safety Supervisor',
    description: '学习食品安全和卫生管理。',
    category: 'cookery',
    type: 'short-course',
    duration: '1天',
    price: 180,
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },
  {
    id: 'rsa',
    title: 'Responsible Service of Alcohol (RSA) - NSW',
    description: '负责任服务酒精的原则。',
    category: 'hospitality',
    type: 'short-course',
    duration: '1天',
    price: 189,
    image: '/rsa_banner.png',
    link: '/cookery-and-hospitality-courses/rsa',
    tags: ['RSA', 'Alcohol', 'liquor laws', 'nsw'],
  },
  // Hospitality Courses
  {
    id: 'hospitality-diploma',
    title: 'Diploma of Hospitality Management',
    description: '全面的酒店管理技能。',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78周 / 104周',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: 'Advanced Diploma of Hospitality Management',
    description: '高级酒店管理和领导技能。',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104周',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },
  // Fitness Courses
  {
    id: 'fitness-cert-iii',
    title: 'Certificate III in Fitness',
    description: '基础健身和个人训练技能。',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52周',
    image: '/courses/fitness/ABM_Fitness_Photos_13.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: 'Certificate IV in Fitness',
    description: '高级健身训练和指导技能。',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52周',
    image: '/courses/fitness/ABM_Fitness_Photos_10.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: 'Certificate III in Fitness (Fast Track)',
    description: '加速的体育教练和训练计划。',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12周 / 24周',
    image: '/courses/fitness/ABM_Fitness_Photos_11.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: 'Certificate IV in Fitness (Fast Track)',
    description: '高级体育教练和发展计划。',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12周 / 24周',
    image: '/courses/fitness/ABM_Fitness_Photos_9.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: 'Diploma of Sport',
    description: '全面的体育教练和发展计划。',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52周',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },
  // Business Courses
  {
    id: 'business-cert-iv',
    title: 'Certificate IV in Business',
    description: '基础商业技能和知识。',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52周',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: 'Diploma of Business',
    description: '全面的商业管理和领导技能。',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52周',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: 'Advanced Diploma of Business',
    description: '高级商业战略和管理技能。',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78周',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: 'Graduate Diploma of Management (Learning)',
    description: '研究生级别的管理和领导技能。',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52周',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },

  // Project Management Courses
  {
    id: 'project-cert-iv',
    title: 'Certificate IV in Project Management Practice',
    description: '基础项目管理技能和方法论。',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52周',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: 'Diploma of Project Management',
    description: '全面的项目管理和领导技能。',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52周',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: 'Advanced Diploma of Program Management',
    description: '高级项目管理和战略规划技能。',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78周',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },

  // HR Courses
  {
    id: 'hr-certificate-iv',
    title: 'Certificate IV in Human Resource Management',
    description: '培养入门级职位所需的人力资源技能。',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52周',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'certificate-iv'],
  },
  {
    id: 'hr-diploma',
    title: 'Diploma of Human Resource Management',
    description: '高级人力资源管理和战略思维。',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '78周',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'diploma'],
  },
  {
    id: 'hr-advanced-diploma',
    title: 'Advanced Diploma of Human Resource Management',
    description: '高级人力资源领导和战略管理技能。',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78周',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'leadership', 'advanced-diploma'],
  },

  // Health & Wellness Courses
  {
    id: 'health-services-assistance',
    title: 'HLT33115 Certificate III in Health Services Assistance',
    description:
      '通过这个全面的护理支持通道开始您的医疗保健职业，包括英语语言支持和80小时的工作实习。',
    category: 'health',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '16周',
    image: '/courses/health/health_1.png',
    link: '/health-and-wellness-courses/hlt33115-certificate-iii-in-health-services-assistance',
    tags: [
      'health',
      'nursing',
      'healthcare',
      'certificate-iii',
      'work-placement',
    ],
  },

  // Custom Programs
  {
    id: 'custom-programs',
    title: '定制课程',
    description:
      '为机构、大学和学院量身定制的课程。我们与教育机构合作，提供符合其课程设置、学习目标和学生需求的定制课程。',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '灵活',
    image: '/custom_program_1.png',
    link: '/custom-programs',
    tags: ['custom', 'programs', 'tailored', 'institutions', 'partnership'],
  },
];
