import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // Cookery Courses
  {
    id: 'kitchen-management',
    title: 'Certificate IV in Kitchen Management',
    description:
      'Matuto ng propesyonal na kasanayan sa pamamahala ng kusina at mga teknik sa pagluluto.',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78 linggo',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'NSW Food Safety Supervisor',
    description: 'Matuto ng kaligtasan sa pagkain at pamamahala ng kalinisan.',
    category: 'cookery',
    type: 'short-course',
    duration: '1 araw',
    price: 180,
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },
  {
    id: 'rsa',
    title: 'Responsible Service of Alcohol (RSA) - NSW',
    description: 'Ang mga prinsipyo ng Responsableng Serbisyo ng Alak.',
    category: 'hospitality',
    type: 'short-course',
    duration: '1 araw',
    price: 189,
    image: '/rsa_banner.png',
    link: '/cookery-and-hospitality-courses/rsa',
    tags: ['RSA', 'Alcohol', 'liquor laws', 'nsw'],
  },
  // Hospitality Courses
  {
    id: 'hospitality-diploma',
    title: 'Diploma of Hospitality Management',
    description: 'Komprehensibong kasanayan sa pamamahala ng hospitality.',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78 linggo / 104 linggo',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: 'Advanced Diploma of Hospitality Management',
    description: 'Advanced na kasanayan sa pamamahala at pamumuno sa hospitality.',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104 linggo',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },
  // Fitness Courses
  {
    id: 'fitness-cert-iii',
    title: 'Certificate III in Fitness',
    description: 'Pangunahing kasanayan sa fitness at personal na pagsasanay.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52 linggo',
    image: '/courses/fitness/ABM_Fitness_Photos_13.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: 'Certificate IV in Fitness',
    description: 'Advanced na kasanayan sa pagsasanay at pagtuturo ng fitness.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 linggo',
    image: '/courses/fitness/ABM_Fitness_Photos_10.jpg',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: 'Certificate III in Fitness (Fast Track)',
    description: 'Pinabilis na programa ng pagsasanay sa sports coaching.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12 linggo / 24 linggo',
    image: '/courses/fitness/ABM_Fitness_Photos_11.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: 'Certificate IV in Fitness (Fast Track)',
    description: 'Advanced na programa ng sports coaching at development.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12 linggo / 24 linggo',
    image: '/courses/fitness/ABM_Fitness_Photos_9.jpg',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: 'Diploma of Sport',
    description: 'Komprehensibong programa ng sports coaching at development.',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52 linggo',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },
  // Business Courses
  {
    id: 'business-cert-iv',
    title: 'Certificate IV in Business',
    description: 'Pangunahing kasanayan at kaalaman sa negosyo.',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 linggo',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: 'Diploma of Business',
    description: 'Komprehensibong kasanayan sa pamamahala at pamumuno sa negosyo.',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52 linggo',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: 'Advanced Diploma of Business',
    description: 'Advanced na kasanayan sa estratehiya at pamamahala ng negosyo.',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 linggo',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: 'Graduate Diploma of Management (Learning)',
    description: 'Kasanayan sa pamamahala at pamumuno sa antas ng postgraduate.',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52 linggo',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },

  // Project Management Courses
  {
    id: 'project-cert-iv',
    title: 'Certificate IV in Project Management Practice',
    description: 'Pangunahing kasanayan at metodolohiya sa pamamahala ng proyekto.',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 linggo',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: 'Diploma of Project Management',
    description: 'Komprehensibong kasanayan sa pamamahala at pamumuno ng proyekto.',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52 linggo',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: 'Advanced Diploma of Program Management',
    description: 'Advanced na kasanayan sa pamamahala ng proyekto at estratehikong pagpaplano.',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 linggo',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },

  // HR Courses
  {
    id: 'hr-certificate-iv',
    title: 'Certificate IV in Human Resource Management',
    description: 'Bumuo ng mga kasanayan sa HR para sa mga entry-level na posisyon.',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 linggo',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'certificate-iv'],
  },
  {
    id: 'hr-diploma',
    title: 'Diploma of Human Resource Management',
    description: 'Advanced na pamamahala ng HR at estratehikong pag-iisip.',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '78 linggo',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'diploma'],
  },
  {
    id: 'hr-advanced-diploma',
    title: 'Advanced Diploma of Human Resource Management',
    description: 'Senior na kasanayan sa pamumuno at estratehikong pamamahala ng HR.',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 linggo',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'leadership', 'advanced-diploma'],
  },

  // Health & Wellness Courses
  {
    id: 'health-services-assistance',
    title: 'HLT33115 Certificate III in Health Services Assistance',
    description:
      'Simulan ang iyong karera sa healthcare sa komprehensibong nursing support pathway na ito kasama ang suporta sa wikang Ingles at 80 oras ng work placement.',
    category: 'health',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '16 linggo',
    image: '/courses/health/health_1.png',
    link: '/health-and-wellness-courses/hlt33115-certificate-iii-in-health-services-assistance',
    tags: [
      'health',
      'nursing',
      'healthcare',
      'certificate-iii',
      'work-placement',
    ],
  },

  // Custom Programs
  {
    id: 'custom-programs',
    title: 'Custom Programs',
    description:
      'Mga naka-customize na programa para sa mga institusyon, unibersidad, at kolehiyo. Nakikipagtulungan kami sa mga institusyong pang-edukasyon upang maghatid ng mga customized na programa na tumutugma sa kanilang kurikulum, mga layunin sa pag-aaral, at mga pangangailangan ng estudyante.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: 'Flexible',
    image: '/custom_program_1.png',
    link: '/custom-programs',
    tags: ['custom', 'programs', 'tailored', 'institutions', 'partnership'],
  },
];
