import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // 조리 과정
  {
    id: 'kitchen-management',
    title: '주방 관리 4급 자격증',
    description: '전문적인 주방 관리 기술과 요리 기법을 배웁니다.',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78주',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'NSW 식품 안전 관리자',
    description: '식품 안전 및 위생 관리법을 배웁니다.',
    category: 'cookery',
    type: 'short-course',
    price: 180,
    duration: '1일',
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },
  // 호텔경영 과정
  {
    id: 'hospitality-diploma',
    title: '호텔경영 디플로마',
    description: '호텔경영에 필요한 종합적인 관리 역량을 배웁니다.',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78주 / 104주',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: '호텔경영 고급 디플로마',
    description: '고급 호텔경영 및 리더십 역량을 배웁니다.',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104주',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },
  // 피트니스 과정
  {
    id: 'fitness-cert-iii',
    title: '피트니스 3급 자격증',
    description: '기초 피트니스 및 퍼스널 트레이닝 역량을 배웁니다.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52주',
    image: '/courses/fitness/fitness_1.png',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: '피트니스 4급 자격증',
    description: '고급 피트니스 트레이닝 및 지도 역량을 배웁니다.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/fitness/fitness_5-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: '피트니스 3급 자격증 (패스트트랙)',
    description: '스포츠 코칭 및 트레이닝을 빠르게 배우는 과정입니다.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12주 / 24주',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: '피트니스 4급 자격증 (패스트트랙)',
    description: '고급 스포츠 코칭 및 개발 프로그램입니다.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12주 / 24주',
    image: '/courses/fitness/fitness_3-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: '스포츠 디플로마',
    description: '스포츠 코칭 및 개발에 대한 종합 프로그램입니다.',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/fitness/fitness_2-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },
  // 비즈니스 과정
  {
    id: 'business-cert-iv',
    title: '비즈니스 4급 자격증',
    description: '비즈니스의 기초 역량과 지식을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: '비즈니스 디플로마',
    description: '비즈니스 관리 및 리더십에 대한 종합 역량을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: '비즈니스 고급 디플로마',
    description: '고급 비즈니스 전략 및 경영 역량을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78주',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: '경영학 석사 디플로마',
    description: '석사 수준의 경영 및 리더십 역량을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52주',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },
  // 프로젝트 관리 과정
  {
    id: 'project-cert-iv',
    title: '프로젝트 관리 4급 자격증',
    description: '프로젝트 관리의 기초 역량과 방법론을 배웁니다.',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: '프로젝트 관리 디플로마',
    description: '프로젝트 관리 및 리더십에 대한 종합 역량을 배웁니다.',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: '프로젝트 관리 고급 디플로마',
    description: '고급 프로젝트 관리 및 전략적 기획 역량을 배웁니다.',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78주',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },
  // 인사관리 과정
  {
    id: 'hr-cert-iv',
    title: '인사관리 4급 자격증',
    description: '기초 인사관리 역량과 실무를 배웁니다.',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'certificate-iv', 'management'],
  },
  {
    id: 'hr-diploma',
    title: '인사관리 디플로마',
    description: '인사관리 및 조직관리 종합 역량을 배웁니다.',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'diploma', 'organizational'],
  },
  {
    id: 'hr-advanced-diploma',
    title: '인사관리 고급 디플로마',
    description: '고급 인사 전략 및 조직 개발 역량을 배웁니다.',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78주',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'advanced-diploma', 'strategy'],
  },
  // 단기과정 - 호텔
  {
    id: 'barista',
    title: '원데이 바리스타 클래스 ☕️',
    description:
      '단 하루 만에 완벽한 에스프레소, 부드러운 우유 거품, 멋진 라떼아트까지 배워보세요!',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '4시간',
    price: 150,
    image: '/short-course/barista_1.jpg',
    link: '/short-courses/barista',
    tags: ['barista', 'coffee', 'latte-art', 'one-day', 'hands-on'],
  },
  {
    id: 'wine',
    title: '와인 감별 클래스 🍷',
    description: '와인 종류, 테이스팅 기법, 음식 페어링을 배웁니다.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '3시간',
    price: 120,
    image: '/short-course/wine/wine_1.jpg',
    link: '/short-courses/wine',
    tags: ['wine', 'appreciation', 'tasting', 'food-pairing'],
  },
  {
    id: 'dessert-plating',
    title: '파인다이닝 디저트 플레이팅 클래스 🍰',
    description: '전문적인 디저트 플레이팅과 프레젠테이션을 마스터하세요.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '4시간',
    price: 140,
    image: '/short-course/dessert/fine_dining_dessert_1.jpg',
    link: '/short-courses/dessert',
    tags: ['dessert', 'plating', 'fine-dining', 'presentation'],
  },
  {
    id: 'cocktail',
    title: '칵테일 & 믹솔로지 클래스 🍹',
    description: '칵테일 제조와 믹솔로지 기법을 마스터하세요.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '3시간',
    price: 130,
    image: '/short-course/mixology/cocktail_1.png',
    link: '/short-courses/mixology',
    tags: ['cocktail', 'mixology', 'bartending', 'drinks'],
  },
  {
    id: 'fss',
    title: 'NSW 식품 안전 관리자 자격증',
    description: 'NSW에서 인증받은 식품 안전 관리자가 되어보세요.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '1일',
    price: 100,
    image: '/home/Cookery.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'supervisor', 'certification', 'nsw'],
  },
  // 단기과정 - 제과제빵
  {
    id: 'french-cakes',
    title: '프랑스 클래식 케이크 마스터클래스 🍰',
    description:
      '오페라 케이크, 레몬 타르트 등 멋진 프랑스식 케이크를 배워보세요.',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '5.5시간',
    price: 180,
    image: '/short-course/classic_french_cakes_2.png',
    link: '/short-courses/cake',
    tags: ['french-cakes', 'pastry', 'baking', 'masterclass'],
  },
  {
    id: 'sourdough',
    title: '사워도우 & 포카치아 마스터클래스 🥖✨',
    description: '수상 경력의 전문가와 함께하는 장인급 사워도우 빵 만들기.',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '5.5시간',
    price: 160,
    image: '/short-course/focaccia/sourdough_1.jpg',
    link: '/short-courses/focaccia',
    tags: ['sourdough', 'bread', 'focaccia', 'artisan', 'baking'],
  },
  {
    id: 'french-pastries',
    title: '프랑스 클래식 페이스트리 클래스 🥐',
    description: '정통 프랑스 페이스트리와 비에누와즈리를 배워보세요.',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '6시간',
    price: 190,
    image: '/short-course/classic_french_pastries_1.png',
    link: '/short-courses/pastries',
    tags: ['french-pastries', 'viennoiserie', 'baking', 'authentic'],
  },
  {
    id: 'macaron',
    title: '프랑스 마카롱 & 쁘띠푸르 클래스 🍪',
    description: '완벽한 프랑스 마카롱과 쁘띠푸르를 만들어보세요.',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '4시간',
    price: 150,
    image: '/short-course/macaroon_1.png',
    link: '/short-courses/petit',
    tags: ['macaron', 'petit-four', 'french', 'delicate'],
  },
  {
    id: 'vegan',
    title: '비건 & 채식 클래스 🌱',
    description: '식물성 재료로 만드는 다양한 요리법을 배워보세요.',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '4시간',
    price: 140,
    image: '/short-course/vegan/vegan_1.png',
    link: '/short-courses/vegan',
    tags: ['vegan', 'vegetarian', 'plant-based', 'healthy'],
  },
  {
    id: 'chocolate',
    title: '초콜릿 클래스 – 크리스마스 🍫',
    description: '연말 분위기의 초콜릿 디저트와 선물용 과자를 만들어보세요.',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '3시간',
    price: 120,
    image: '/short-course/chocolate/xmas_1.png',
    link: '/short-courses/chocolate',
    tags: ['chocolate', 'christmas', 'festive', 'holiday'],
  },
];
