import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // Cursos de Culinária
  {
    id: 'kitchen-management',
    title: 'Certificado IV em Gestão de Cozinha',
    description:
      'Aprenda técnicas profissionais de culinária e gestão de cozinha.',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78 semanas',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['cozinha', 'gestão', 'culinária', 'certificado-iv'],
  },
  {
    id: 'food-safety',
    title: 'Supervisor de Segurança Alimentar NSW',
    description: 'Aprenda gestão de segurança e higiene alimentar.',
    category: 'cookery',
    type: 'short-course',
    duration: '1 dia',
    price: 180,
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['segurança-alimentar', 'higiene', 'supervisor', 'nsw'],
  },
  {
    id: 'rsa',
    title: 'Responsible Service of Alcohol (RSA) - NSW',
    description: 'Os princípios do Serviço Responsável de Álcool.',
    category: 'hospitality',
    type: 'short-course',
    duration: '1 dia',
    price: 189,
    image: '/rsa_banner.png',
    link: '/cookery-and-hospitality-courses/rsa',
    tags: ['RSA', 'Alcohol', 'liquor laws', 'nsw'],
  },
  // Cursos de Hospitalidade
  {
    id: 'hospitality-diploma',
    title: 'Diploma em Gestão de Hospitalidade',
    description: 'Aprenda habilidades abrangentes de gestão em hospitalidade.',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78 semanas / 104 semanas',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitalidade', 'gestão', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: 'Diploma Avançado em Gestão de Hospitalidade',
    description:
      'Aprimore suas habilidades de liderança e gestão avançada em hospitalidade.',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104 semanas',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitalidade', 'gestão', 'diploma-avançado', 'liderança'],
  },

  // Cursos de Fitness
  {
    id: 'fitness-cert-iii',
    title: 'Certificado III em Fitness',
    description:
      'Aprenda fundamentos de treinamento físico e personal trainer.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52 semanas',
    image: '/courses/fitness/fitness_1.png',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-trainer', 'certificado-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: 'Certificado IV em Fitness',
    description:
      'Aprimore suas habilidades avançadas de treinamento e instrução física.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/fitness/fitness_5-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-trainer', 'certificado-iv', 'avançado'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: 'Certificado III em Fitness (Intensivo)',
    description: 'Programa acelerado de treinamento e coaching esportivo.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12 semanas / 24 semanas',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['esporte', 'coaching', 'intensivo', 'certificado-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: 'Certificado IV em Fitness (Intensivo)',
    description: 'Programa avançado de desenvolvimento e coaching esportivo.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12 semanas / 24 semanas',
    image: '/courses/fitness/fitness_3-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['esporte', 'coaching', 'intensivo', 'certificado-iv', 'avançado'],
  },
  {
    id: 'sport-diploma',
    title: 'Diploma em Esportes',
    description: 'Programa completo de desenvolvimento e coaching esportivo.',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52 semanas',
    image: '/courses/fitness/fitness_2-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['esporte', 'coaching', 'diploma', 'desenvolvimento'],
  },

  // Cursos de Negócios
  {
    id: 'business-cert-iv',
    title: 'Certificado IV em Negócios',
    description: 'Aprenda fundamentos essenciais de negócios e gestão.',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['negócios', 'gestão', 'certificado-iv'],
  },
  {
    id: 'business-diploma',
    title: 'Diploma em Negócios',
    description:
      'Desenvolva competências amplas em gestão e liderança empresarial.',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52 semanas',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['negócios', 'gestão', 'diploma', 'liderança'],
  },
  {
    id: 'business-advanced-diploma',
    title: 'Diploma Avançado em Negócios',
    description: 'Aprenda estratégias empresariais e gestão avançada.',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 semanas',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['negócios', 'gestão', 'estratégia', 'diploma-avançado'],
  },
  {
    id: 'business-graduate-diploma',
    title: 'Diploma de Pós-Graduação em Gestão (Aprendizagem)',
    description:
      'Habilidades avançadas de gestão e liderança em nível de pós-graduação.',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52 semanas',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['negócios', 'gestão', 'liderança', 'pós-graduação'],
  },

  // Cursos de Gestão de Projetos
  {
    id: 'project-cert-iv',
    title: 'Certificado IV em Prática de Gestão de Projetos',
    description: 'Aprenda fundamentos e metodologias de gestão de projetos.',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['gestão-de-projetos', 'certificado-iv', 'metodologias'],
  },
  {
    id: 'project-diploma',
    title: 'Diploma em Gestão de Projetos',
    description: 'Habilidades abrangentes de gestão e liderança em projetos.',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52 semanas',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['gestão-de-projetos', 'diploma', 'liderança'],
  },
  {
    id: 'project-advanced-diploma',
    title: 'Diploma Avançado em Gestão de Programas',
    description: 'Gestão estratégica e avançada de projetos e programas.',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 semanas',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: [
      'gestão-de-projetos',
      'diploma-avançado',
      'planejamento-estratégico',
    ],
  },

  // Cursos de RH
  {
    id: 'hr-certificate-iv',
    title: 'Certificado IV em Gestão de Recursos Humanos',
    description: 'Desenvolva habilidades para cargos de entrada em RH.',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['rh', 'recursos-humanos', 'gestão', 'certificado-iv'],
  },
  {
    id: 'hr-diploma',
    title: 'Diploma em Gestão de Recursos Humanos',
    description: 'Habilidades avançadas em gestão estratégica de pessoas.',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '78 semanas',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['rh', 'recursos-humanos', 'gestão', 'diploma'],
  },
  {
    id: 'hr-advanced-diploma',
    title: 'Diploma Avançado em Gestão de Recursos Humanos',
    description: 'Liderança sênior e estratégias de gestão de RH.',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 semanas',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['rh', 'recursos-humanos', 'liderança', 'diploma-avançado'],
  },

  // Cursos de Saúde e Bem-Estar
  {
    id: 'health-services-assistance',
    title: 'Certificado III em Assistência de Serviços de Saúde (HLT33115)',
    description:
      'Inicie sua carreira na área da saúde com este curso abrangente que inclui suporte de enfermagem, apoio ao inglês e 80 horas de estágio prático.',
    category: 'health',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '16 semanas',
    image: '/courses/health/health_1.png',
    link: '/health-and-wellness-courses/hlt33115-certificate-iii-in-health-services-assistance',
    tags: ['saúde', 'enfermagem', 'assistência', 'certificado-iii', 'estágio'],
  },

  // Custom Programs
  {
    id: 'custom-programs',
    title: 'Programas Personalizados',
    description:
      'Programas personalizados para instituições, universidades e faculdades. Fazemos parceria com instituições educacionais para oferecer programas personalizados que correspondem ao currículo, objetivos de aprendizagem e necessidades dos alunos.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: 'Flexível',
    image: '/custom_program.png',
    link: '/custom-programs',
    tags: ['custom', 'programs', 'tailored', 'institutions', 'partnership'],
  },
];
