import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // Cookery Courses
  {
    id: 'kitchen-management',
    title: 'キッチンマネジメント IV級 認定資格',
    description: 'プロのキッチンマネジメントと調理技術を学びます。',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78週間',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'NSW フードセーフティスーパーバイザー講習',
    description:
      '食品安全と衛生管理を学び、認定スーパーバイザーになりましょう。',
    category: 'cookery',
    type: 'short-course',
    duration: '1日',
    price: 180,
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },

  // Hospitality Courses
  {
    id: 'hospitality-diploma',
    title: 'ホスピタリティマネジメント ディプロマ',
    description: 'ホスピタリティ分野で必要な包括的な管理スキルを習得します。',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78週間 / 104週間',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: 'ホスピタリティマネジメント 上級ディプロマ',
    description:
      'ホスピタリティ分野における高度なリーダーシップと管理スキルを学びます。',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104週間',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },

  // Fitness Courses
  {
    id: 'fitness-cert-iii',
    title: 'フィットネス III級 認定資格',
    description:
      '基礎的なフィットネス知識とパーソナルトレーニングスキルを学びます。',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52週間',
    image: '/courses/fitness/fitness_1.png',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: 'フィットネス IV級 認定資格',
    description: '高度なフィットネストレーニングと指導スキルを習得します。',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52週間',
    image: '/courses/fitness/fitness_5-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: 'フィットネス III級（短期集中コース）',
    description:
      'スポーツコーチングとトレーニングを加速的に学ぶプログラムです。',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12週間 / 24週間',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: 'フィットネス IV級（短期集中コース）',
    description:
      '上級スポーツコーチングとトレーニングスキルを短期間で習得します。',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12週間 / 24週間',
    image: '/courses/fitness/fitness_3-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: 'スポーツ ディプロマ',
    description: 'スポーツコーチングと選手育成に関する包括的なプログラムです。',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52週間',
    image: '/courses/fitness/fitness_2-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },

  // Business Courses
  {
    id: 'business-cert-iv',
    title: 'ビジネス IV級 認定資格',
    description: 'ビジネスの基礎知識とスキルを学びます。',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52週間',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: 'ビジネス ディプロマ',
    description:
      '包括的なビジネスマネジメントとリーダーシップスキルを養います。',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52週間',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: 'ビジネス 上級ディプロマ',
    description: '高度なビジネス戦略とマネジメントスキルを学びます。',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78週間',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: '経営学大学院ディプロマ（学習専攻）',
    description: '大学院レベルの経営・リーダーシップスキルを習得します。',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52週間',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },

  // Project Management Courses
  {
    id: 'project-cert-iv',
    title: 'プロジェクトマネジメント IV級 認定資格',
    description: 'プロジェクト管理の基礎スキルと手法を学びます。',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52週間',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: 'プロジェクトマネジメント ディプロマ',
    description: '包括的なプロジェクト管理とリーダーシップスキルを養います。',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52週間',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: 'プログラムマネジメント 上級ディプロマ',
    description: '高度なプロジェクト戦略と計画立案スキルを学びます。',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78週間',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },

  // HR Courses
  {
    id: 'hr-certificate-iv',
    title: '人材マネジメント IV級 認定資格',
    description:
      '人事分野の基礎スキルを身につけ、エントリーレベルのキャリアを目指します。',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52週間',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'certificate-iv'],
  },
  {
    id: 'hr-diploma',
    title: '人材マネジメント ディプロマ',
    description: '戦略的思考を伴う上級人事マネジメントスキルを学びます。',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '78週間',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'management', 'diploma'],
  },
  {
    id: 'hr-advanced-diploma',
    title: '人材マネジメント 上級ディプロマ',
    description: '上級管理職に必要な人事戦略とリーダーシップを学びます。',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78週間',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'leadership', 'advanced-diploma'],
  },

  // Health & Wellness Courses
  {
    id: 'health-services-assistance',
    title: '医療サービス支援 III級 認定資格（HLT33115）',
    description:
      '英語サポートと80時間の実習を含む包括的な看護支援キャリアパスをスタート。',
    category: 'health',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '16週間',
    image: '/courses/health/health_1.png',
    link: '/health-and-wellness-courses/hlt33115-certificate-iii-in-health-services-assistance',
    tags: [
      'health',
      'nursing',
      'healthcare',
      'certificate-iii',
      'work-placement',
    ],
  },

  // Short Courses - Hospitality
  {
    id: 'barista',
    title: '1日バリスタクラス ☕️',
    description:
      'エスプレッソの抽出からラテアートまで、1日で学べる実践的なクラスです！',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '4時間',
    price: 150,
    image: '/short-course/barista_1.jpg',
    link: '/short-courses/barista',
    tags: ['barista', 'coffee', 'latte-art', 'one-day', 'hands-on'],
  },
  {
    id: 'wine',
    title: 'ワインテイスティング講座 🍷',
    description:
      'ワインの種類、テイスティング技法、料理とのペアリングを学びます。',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '3時間',
    price: 120,
    image: '/short-course/wine/wine_1.jpg',
    link: '/short-courses/wine',
    tags: ['wine', 'appreciation', 'tasting', 'food-pairing'],
  },
  {
    id: 'dessert-plating',
    title: 'デザート盛り付けマスタークラス 🍰',
    description: 'プロフェッショナルなデザートプレーティング技法を学びます。',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '4時間',
    price: 140,
    image: '/short-course/dessert/fine_dining_dessert_1.jpg',
    link: '/short-courses/dessert',
    tags: ['dessert', 'plating', 'fine-dining', 'presentation'],
  },
  {
    id: 'cocktail',
    title: 'カクテル＆ミクソロジー講座 🍹',
    description: 'クラシックから創作まで、カクテル作りの技術を学びます。',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '3時間',
    price: 130,
    image: '/short-course/mixology/cocktail_1.png',
    link: '/short-courses/mixology',
    tags: ['cocktail', 'mixology', 'bartending', 'drinks'],
  },
  {
    id: 'fss',
    title: 'NSW フードセーフティ再認定講習',
    description:
      'NSW州で認定フードセーフティスーパーバイザーを目指しましょう。',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '1日',
    price: 100,
    image: '/home/Cookery.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'supervisor', 'certification', 'nsw'],
  },

  // Short Courses - Cooking & Baking
  {
    id: 'french-cakes',
    title: 'クラシックフレンチケーキ講座 🍰',
    description:
      'オペラケーキやレモンタルトなど、美しいフレンチペストリーを作りましょう。',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '5.5時間',
    price: 180,
    image: '/short-course/classic_french_cakes_2.png',
    link: '/short-courses/cake',
    tags: ['french-cakes', 'pastry', 'baking', 'masterclass'],
  },
  {
    id: 'sourdough',
    title: 'サワードウ＆フォカッチャ講座 🥖✨',
    description:
      '受賞歴のあるパン職人からアーティザンブレッド作りの技を学びます。',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '5.5時間',
    price: 160,
    image: '/short-course/focaccia/sourdough_1.jpg',
    link: '/short-courses/focaccia',
    tags: ['sourdough', 'bread', 'focaccia', 'artisan', 'baking'],
  },
  {
    id: 'french-pastries',
    title: 'クラシックフレンチペストリー講座 🥐',
    description: '本格的なフレンチペストリーとヴィエノワズリーを学びます。',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '6時間',
    price: 190,
    image: '/short-course/classic_french_pastries_1.png',
    link: '/short-courses/pastries',
    tags: ['french-pastries', 'viennoiserie', 'baking', 'authentic'],
  },
  {
    id: 'macaron',
    title: 'プチフール講座（マカロン）🍪',
    description: '完璧なフレンチマカロンとプチフールの作り方を学びます。',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '4時間',
    price: 150,
    image: '/short-course/macaroon_1.png',
    link: '/short-courses/petit',
    tags: ['macaron', 'petit-four', 'french', 'delicate'],
  },
  {
    id: 'vegan',
    title: 'ヴィーガン＆ベジタリアン料理講座 🌱',
    description: '植物由来の食材を使った料理技法とレシピを学びます。',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '4時間',
    price: 140,
    image: '/short-course/vegan/vegan_1.png',
    link: '/short-courses/vegan',
    tags: ['vegan', 'vegetarian', 'plant-based', 'healthy'],
  },
  {
    id: 'chocolate',
    title: 'チョコレートクラス – クリスマス特別講座 🍫',
    description:
      'ホリデーシーズンにぴったりなチョコレートスイーツとお菓子を作りましょう。',
    category: 'short-course-cooking',
    type: 'short-course',
    duration: '3時間',
    price: 120,
    image: '/short-course/chocolate/xmas_1.png',
    link: '/short-courses/chocolate',
    tags: ['chocolate', 'christmas', 'festive', 'holiday'],
  },
];
