import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // Cursos de Cocina
  {
    id: 'kitchen-management',
    title: 'Certificado IV en Gestión de Cocina',
    description:
      'Aprende habilidades profesionales de gestión de cocina y técnicas culinarias.',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78 semanas',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'Supervisor de Seguridad Alimentaria de NSW',
    description: 'Aprende sobre seguridad alimentaria y gestión de higiene.',
    category: 'cookery',
    type: 'short-course',
    price: 180,
    duration: '1 día',
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },
  {
    id: 'rsa',
    title: 'Responsible Service of Alcohol (RSA) - NSW',
    description: 'Los principios del servicio responsable de alcohol.',
    category: 'hospitality',
    type: 'short-course',
    duration: '1 día',
    price: 189,
    image: '/rsa_banner.png',
    link: '/cookery-and-hospitality-courses/rsa',
    tags: ['RSA', 'Alcohol', 'liquor laws', 'nsw'],
  },
  // Cursos de Hospitalidad
  {
    id: 'hospitality-diploma',
    title: 'Diplomado en Gestión de Hospitalidad',
    description: 'Habilidades integrales de gestión en hospitalidad.',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78 semanas / 104 semanas',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: 'Diplomado Avanzado en Gestión de Hospitalidad',
    description:
      'Habilidades avanzadas de gestión y liderazgo en hospitalidad.',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104 semanas',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },
  // Cursos de Fitness
  {
    id: 'fitness-cert-iii',
    title: 'Certificado III en Fitness',
    description:
      'Habilidades fundamentales en fitness y entrenamiento personal.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52 semanas',
    image: '/courses/fitness/fitness_1.png',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: 'Certificado IV en Fitness',
    description:
      'Habilidades avanzadas de entrenamiento y enseñanza en fitness.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/fitness/fitness_5-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: 'Certificado III en Fitness (Rápido)',
    description: 'Programa acelerado de entrenamiento y coaching deportivo.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12 semanas / 24 semanas',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: 'Certificado IV en Fitness (Rápido)',
    description: 'Programa avanzado de coaching y desarrollo deportivo.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12 semanas / 24 semanas',
    image: '/courses/fitness/fitness_3-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: 'Diplomado en Deporte',
    description: 'Programa integral de coaching y desarrollo deportivo.',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52 semanas',
    image: '/courses/fitness/fitness_2-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },
  // Cursos de Negocios
  {
    id: 'business-cert-iv',
    title: 'Certificado IV en Negocios',
    description: 'Habilidades y conocimientos fundamentales en negocios.',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: 'Diplomado en Negocios',
    description: 'Habilidades integrales de gestión y liderazgo empresarial.',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52 semanas',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: 'Diplomado Avanzado en Negocios',
    description: 'Habilidades avanzadas de estrategia y gestión empresarial.',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 semanas',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: 'Diplomado de Posgrado en Gestión',
    description: 'Habilidades de gestión y liderazgo a nivel de posgrado.',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52 semanas',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },
  // Cursos de Gestión de Proyectos
  {
    id: 'project-cert-iv',
    title: 'Certificado IV en Gestión de Proyectos',
    description:
      'Habilidades y metodologías fundamentales en gestión de proyectos.',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: 'Diplomado en Gestión de Proyectos',
    description: 'Habilidades integrales de gestión y liderazgo de proyectos.',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52 semanas',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: 'Diplomado Avanzado en Gestión de Proyectos',
    description:
      'Habilidades avanzadas en gestión de proyectos y planificación estratégica.',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 semanas',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },
  // Cursos de Recursos Humanos
  {
    id: 'hr-cert-iv',
    title: 'Certificado IV en Gestión de Recursos Humanos',
    description: 'Habilidades y prácticas fundamentales en gestión de RRHH.',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52 semanas',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'certificate-iv', 'management'],
  },
  {
    id: 'hr-diploma',
    title: 'Diplomado en Gestión de Recursos Humanos',
    description:
      'Habilidades integrales de gestión de RRHH y organizacionales.',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '52 semanas',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'diploma', 'organizational'],
  },
  {
    id: 'hr-advanced-diploma',
    title: 'Diplomado Avanzado en Gestión de Recursos Humanos',
    description:
      'Habilidades avanzadas de estrategia y desarrollo organizacional en RRHH.',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78 semanas',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'advanced-diploma', 'strategy'],
  },

  // Custom Programs
  {
    id: 'custom-programs',
    title: 'Programas Personalizados',
    description:
      'Programas personalizados para instituciones, universidades y colegios. Nos asociamos con instituciones educativas para ofrecer programas personalizados que se adaptan a su currículo, objetivos de aprendizaje y necesidades de los estudiantes.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: 'Flexible',
    image: '/custom_program.png',
    link: '/custom-programs',
    tags: ['custom', 'programs', 'tailored', 'institutions', 'partnership'],
  },
];
