import { CourseData } from './courseData';

export const courseData: CourseData[] = [
  // 조리 과정
  {
    id: 'kitchen-management',
    title: '주방 관리 4급 자격증',
    description: '전문적인 주방 관리 기술과 요리 기법을 배웁니다.',
    category: 'cookery',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '78주',
    image: '/courses/cookery/KM.png',
    link: '/cookery-and-hospitality-courses/sit40521-certificate-iv-in-kitchen-management',
    tags: ['kitchen', 'management', 'culinary', 'certificate-iv'],
  },
  {
    id: 'food-safety',
    title: 'NSW 식품 안전 관리자',
    description: '식품 안전 및 위생 관리법을 배웁니다.',
    category: 'cookery',
    type: 'short-course',
    price: 180,
    duration: '1일',
    image: '/short-course/fss_1.png',
    link: '/cookery-and-hospitality-courses/fss',
    tags: ['food-safety', 'hygiene', 'supervisor', 'nsw'],
  },
  // 호텔경영 과정
  {
    id: 'hospitality-diploma',
    title: '호텔경영 디플로마',
    description: '호텔경영에 필요한 종합적인 관리 역량을 배웁니다.',
    category: 'hospitality',
    type: 'full-course',
    level: 'diploma',
    duration: '78주 / 104주',
    image: '/courses/cookery/DHM.png',
    link: '/cookery-and-hospitality-courses/sit50422-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'diploma'],
  },
  {
    id: 'hospitality-advanced-diploma',
    title: '호텔경영 고급 디플로마',
    description: '고급 호텔경영 및 리더십 역량을 배웁니다.',
    category: 'hospitality',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '104주',
    image: '/courses/cookery/ADHM.png',
    link: '/cookery-and-hospitality-courses/advanced-diploma-of-hospitality-management',
    tags: ['hospitality', 'management', 'advanced-diploma', 'leadership'],
  },
  // 피트니스 과정
  {
    id: 'fitness-cert-iii',
    title: '피트니스 3급 자격증',
    description: '기초 피트니스 및 퍼스널 트레이닝 역량을 배웁니다.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iii',
    duration: '52주',
    image: '/courses/fitness/fitness_1.png',
    link: '/fitness-instructor-personal-trainer-courses/sis30321-certificate-iii-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv',
    title: '피트니스 4급 자격증',
    description: '고급 피트니스 트레이닝 및 지도 역량을 배웁니다.',
    category: 'fitness',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/fitness/fitness_5-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis40221-certificate-iv-in-fitness',
    tags: ['fitness', 'personal-training', 'certificate-iv', 'advanced'],
  },
  {
    id: 'fitness-cert-iii-fast-track',
    title: '피트니스 3급 자격증 (패스트트랙)',
    description: '스포츠 코칭 및 트레이닝을 빠르게 배우는 과정입니다.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iii',
    duration: '12주 / 24주',
    image: '/courses/fitness/diploma-of-sport.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iii-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iii'],
  },
  {
    id: 'fitness-cert-iv-fast-track',
    title: '피트니스 4급 자격증 (패스트트랙)',
    description: '고급 스포츠 코칭 및 개발 프로그램입니다.',
    category: 'fitness',
    type: 'fast-track',
    level: 'certificate-iv',
    duration: '12주 / 24주',
    image: '/courses/fitness/fitness_3-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/certificate-iv-in-fitness-fast-track',
    tags: ['sport', 'coaching', 'fast-track', 'certificate-iv', 'advanced'],
  },
  {
    id: 'sport-diploma',
    title: '스포츠 디플로마',
    description: '스포츠 코칭 및 개발에 대한 종합 프로그램입니다.',
    category: 'fitness',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/fitness/fitness_2-banner.png',
    link: '/fitness-instructor-personal-trainer-courses/sis50321-diploma-of-sport',
    tags: ['sport', 'coaching', 'diploma', 'development'],
  },
  // 비즈니스 과정
  {
    id: 'business-cert-iv',
    title: '비즈니스 4급 자격증',
    description: '비즈니스의 기초 역량과 지식을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/business/business_1.jpg',
    link: '/business-and-management-courses/bsb40120-certificate-iv-in-business',
    tags: ['business', 'management', 'certificate-iv'],
  },
  {
    id: 'business-diploma',
    title: '비즈니스 디플로마',
    description: '비즈니스 관리 및 리더십에 대한 종합 역량을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/business/business_2.png',
    link: '/business-and-management-courses/bsb50120-diploma-of-business',
    tags: ['business', 'management', 'diploma', 'leadership'],
  },
  {
    id: 'business-advanced-diploma',
    title: '비즈니스 고급 디플로마',
    description: '고급 비즈니스 전략 및 경영 역량을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78주',
    image: '/courses/business/business_3.png',
    link: '/business-and-management-courses/bsb60120-advanced-diploma-of-business',
    tags: ['business', 'management', 'advanced-diploma', 'strategy'],
  },
  {
    id: 'business-graduate-diploma',
    title: '경영학 석사 디플로마',
    description: '석사 수준의 경영 및 리더십 역량을 배웁니다.',
    category: 'business',
    type: 'full-course',
    level: 'graduate-diploma',
    duration: '52주',
    image: '/courses/business/business_4.png',
    link: '/business-and-management-courses/bsb80120-graduate-diploma-of-management',
    tags: ['business', 'management', 'graduate-diploma', 'leadership'],
  },
  // 프로젝트 관리 과정
  {
    id: 'project-cert-iv',
    title: '프로젝트 관리 4급 자격증',
    description: '프로젝트 관리의 기초 역량과 방법론을 배웁니다.',
    category: 'project',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/project/project_1.png',
    link: '/project-and-program-management-courses/bsb40920-certificate-iv-in-project-management-practice',
    tags: ['project-management', 'certificate-iv', 'methodologies'],
  },
  {
    id: 'project-diploma',
    title: '프로젝트 관리 디플로마',
    description: '프로젝트 관리 및 리더십에 대한 종합 역량을 배웁니다.',
    category: 'project',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/project/project_2.png',
    link: '/project-and-program-management-courses/bsb50820-diploma-of-project-management-practice',
    tags: ['project-management', 'diploma', 'leadership'],
  },
  {
    id: 'project-advanced-diploma',
    title: '프로젝트 관리 고급 디플로마',
    description: '고급 프로젝트 관리 및 전략적 기획 역량을 배웁니다.',
    category: 'project',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78주',
    image: '/courses/project/project_3.png',
    link: '/project-and-program-management-courses/bsb60720-advanced-diploma-of-program-management',
    tags: ['project-management', 'advanced-diploma', 'strategic-planning'],
  },
  // 인사관리 과정
  {
    id: 'hr-cert-iv',
    title: '인사관리 4급 자격증',
    description: '기초 인사관리 역량과 실무를 배웁니다.',
    category: 'hr',
    type: 'full-course',
    level: 'certificate-iv',
    duration: '52주',
    image: '/courses/hr/hr_1.png',
    link: '/human-resources-courses/bsb40420-certificate-iv-in-human-resource-management',
    tags: ['hr', 'human-resources', 'certificate-iv', 'management'],
  },
  {
    id: 'hr-diploma',
    title: '인사관리 디플로마',
    description: '인사관리 및 조직관리 종합 역량을 배웁니다.',
    category: 'hr',
    type: 'full-course',
    level: 'diploma',
    duration: '52주',
    image: '/courses/hr/hr_2.png',
    link: '/human-resources-courses/bsb50320-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'diploma', 'organizational'],
  },
  {
    id: 'hr-advanced-diploma',
    title: '인사관리 고급 디플로마',
    description: '고급 인사 전략 및 조직 개발 역량을 배웁니다.',
    category: 'hr',
    type: 'full-course',
    level: 'advanced-diploma',
    duration: '78주',
    image: '/courses/hr/hr_3.png',
    link: '/human-resources-courses/bsb60320-advanced-diploma-of-human-resource-management',
    tags: ['hr', 'human-resources', 'advanced-diploma', 'strategy'],
  },

  // Custom Programs
  {
    id: 'custom-programs',
    title: '맞춤형 프로그램',
    description:
      '교육 기관, 대학교, 컬리지를 위한 맞춤형 프로그램. 우리는 교육 기관과 파트너십을 맺어 각 기관의 커리큘럼, 학습 목표, 학생의 니즈에 맞는 맞춤형 프로그램을 제공합니다.',
    category: 'short-course-hospitality',
    type: 'short-course',
    duration: '유연',
    image: '/custom_program.png',
    link: '/custom-programs',
    tags: ['custom', 'programs', 'tailored', 'institutions', 'partnership'],
  },
];
